<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Folder Include="IntPrimary\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RapidLaunch\RapidLaunch.csproj" />
  </ItemGroup>

</Project>
