CREATE TABLE [dbo].[GuidPet]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [CustomerId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [GuidCustomer]([Id]) ON DELETE CASCADE ON UPDATE CASCADE
)

GO
