name: main

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.2.0
        with:
          connection-string-env-var: TEST_CONNECTION_STRING
          catalog: RapidLaunch
          extra-params: "TrustServerCertificate=true;"

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Pack
        run: dotnet pack --no-restore --no-build -c Release -o .

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal

    #   - name: Publish
    #     run: dotnet nuget push RapidLaunch.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
